'use strict';
const $=id=>document.getElementById(id), palette=['#2563eb','#8b5cf6','#059669','#e08820'];
let state={areas:window.INITIAL_AREAS.map((a,i)=>({...a,id:'area-'+i})),employees:[],assignments:{},source:'assuntos-folha-pagamento.csv',catalogRevision:window.AREA_REVISION},selected=null,color=palette[0],zoom=1,viewMode='map';
function validState(s){return s&&Array.isArray(s.areas)&&s.areas.length>0&&s.areas.length<=500&&s.areas.every(a=>typeof a.id==='string'&&typeof a.name==='string'&&a.name.length>0&&Array.isArray(a.topics)&&a.topics.every(t=>typeof t==='string'))&&new Set(s.areas.map(a=>a.id)).size===s.areas.length&&Array.isArray(s.employees)&&s.employees.length<=1000&&s.employees.every(e=>typeof e.id==='string'&&typeof e.name==='string'&&e.name.trim()&&typeof e.role==='string'&&/^#[0-9a-f]{6}$/i.test(e.color))&&new Set(s.employees.map(e=>e.id)).size===s.employees.length&&s.assignments&&typeof s.assignments==='object'&&!Array.isArray(s.assignments)&&Object.entries(s.assignments).every(([id,ids])=>s.employees.some(e=>e.id===id)&&Array.isArray(ids)&&ids.every(a=>s.areas.some(x=>x.id===a)));}
try{const saved=JSON.parse(localStorage.getItem('mapa-daily-v1'));if(validState(saved)){state=refreshCatalog(saved,window.INITIAL_AREAS,window.AREA_REVISION);if(state.catalogRevision!==saved.catalogRevision)localStorage.setItem('mapa-daily-v1',JSON.stringify(state))}}catch{}
function toast(message){$('toast').textContent=message;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',3500)}
function save(){try{localStorage.setItem('mapa-daily-v1',JSON.stringify(state));$('save-status').textContent='Salvo neste navegador'}catch{$('save-status').textContent='Não foi possível salvar';toast('O navegador não permitiu salvar. Exporte um backup.')}}
function el(tag,cls,text){const x=document.createElement(tag);if(cls)x.className=cls;if(text!==undefined)x.textContent=text;return x}
function avatar(e){const x=el('span','avatar',e.name.trim().split(/\s+/).map(n=>n[0]).slice(0,2).join('').toUpperCase());x.style.setProperty('--person-color',e.color);return x}
function assign(employeeId,areaId){if(!state.employees.some(e=>e.id===employeeId)||!state.areas.some(a=>a.id===areaId))throw Error('Pessoa ou área inválida.');const ids=state.assignments[employeeId]||[];if(ids.includes(areaId)){toast('Esta pessoa já está nesta área.');return}state.assignments[employeeId]=[...ids,areaId];save();render();toast('Pessoa alocada. Você pode adicionar outras áreas.')}
function dropTarget(node,action){node.addEventListener('dragover',e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';node.classList.add('dragover')});node.addEventListener('dragleave',e=>{if(!node.contains(e.relatedTarget))node.classList.remove('dragover')});node.addEventListener('drop',e=>{e.preventDefault();node.classList.remove('dragover');const id=e.dataTransfer.getData('text/plain');if(state.employees.some(p=>p.id===id))action(id)})}
function drag(node,id){node.draggable=true;node.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',id);e.dataTransfer.effectAllowed='copyMove'})}
function render(){const query=$('search').value.toLocaleLowerCase('pt-BR').trim(),areas=state.areas.filter(a=>(a.name+' '+a.topics.join(' ')).toLocaleLowerCase('pt-BR').includes(query));$('branches').replaceChildren();$('people').replaceChildren();$('area-count').textContent=state.areas.length;$('people-count').textContent=state.employees.length;$('allocated-count').textContent=state.employees.filter(e=>(state.assignments[e.id]||[]).length).length;$('source-label').textContent=state.source||'CSV importado';$('no-results').hidden=areas.length>0;$('map').hidden=!areas.length;
areas.forEach((a,i)=>{const card=el('article','area');card.dataset.id=a.id;card.style.setProperty('--accent',palette[Math.floor(i/2)%palette.length]);card.tabIndex=0;card.setAttribute('aria-label',a.name+(selected?' — alocar pessoa selecionada':''));const heading=el('button','area-title');heading.type='button';heading.append(el('span','area-number',String(state.areas.indexOf(a)+1).padStart(2,'0')),el('span','',a.name),el('span','chevron','+'));heading.setAttribute('aria-expanded','false');const preview=el('p','topics-preview',a.topics.join(' · ')),list=el('ul','topics');list.hidden=true;a.topics.forEach(t=>list.append(el('li','',t)));heading.addEventListener('click',e=>{e.stopPropagation();if(selected){assign(selected,a.id);return}if(viewMode==='compact')return;list.hidden=!list.hidden;preview.hidden=!list.hidden;heading.setAttribute('aria-expanded',String(!list.hidden));heading.lastChild.textContent=list.hidden?'+':'−';requestAnimationFrame(drawLines)});const assigned=el('div','assigned');const people=state.employees.filter(e=>(state.assignments[e.id]||[]).includes(a.id));people.forEach(e=>{const chip=el('div','chip');drag(chip,e.id);chip.append(avatar(e),el('span','',e.name));const remove=el('button','','×');remove.setAttribute('aria-label','Retirar '+e.name+' de '+a.name);remove.addEventListener('click',evt=>{evt.stopPropagation();state.assignments[e.id]=state.assignments[e.id].filter(id=>id!==a.id);save();render()});chip.append(remove);assigned.append(chip)});if(!people.length)assigned.append(el('span','drop-label',selected?'Clique para alocar a pessoa selecionada':'Solte um funcionário aqui'));card.append(heading,preview,list,assigned);dropTarget(card,id=>assign(id,a.id));card.addEventListener('click',e=>{if(selected&&!e.target.closest('button'))assign(selected,a.id)});card.addEventListener('keydown',e=>{if(e.target===card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();if(selected)assign(selected,a.id);else heading.click()}});$('branches').append(card)});
state.employees.forEach(e=>{const person=el('div','person'+(selected===e.id?' selected':''));person.tabIndex=0;person.setAttribute('role','button');person.setAttribute('aria-pressed',String(selected===e.id));person.setAttribute('aria-label','Selecionar '+e.name+' para alocar');drag(person,e.id);const info=el('div','person-info');info.append(el('strong','',e.name),el('small','',e.role||'Funcionário'),el('small','allocation',(state.assignments[e.id]||[]).length+' área(s)'));const del=el('button','delete','×');del.setAttribute('aria-label','Excluir '+e.name);del.addEventListener('click',evt=>{evt.stopPropagation();if(!confirm('Excluir '+e.name+' e suas alocações?'))return;state.employees=state.employees.filter(p=>p.id!==e.id);delete state.assignments[e.id];if(selected===e.id)selected=null;save();render()});const select=()=>{selected=selected===e.id?null:e.id;render();if(selected)toast('Clique em uma área para alocar. Clique na pessoa novamente para cancelar.')};person.addEventListener('click',select);person.addEventListener('keydown',evt=>{if(evt.target===person&&(evt.key==='Enter'||evt.key===' ')){evt.preventDefault();select()}});person.append(el('span','grip','⠿'),avatar(e),info,del);$('people').append(person)});if(!state.employees.length)$('people').append(el('div','empty','Cadastre o time para começar a distribuir as pessoas no mapa.'));requestAnimationFrame(drawLines)}
function drawLines(){if(viewMode==='compact'){fitCompact();return}const map=$('map'),branches=$('branches');map.style.minHeight=Math.max(700,branches.offsetHeight+60)+'px';const root=map.querySelector('.root');root.style.top=Math.max(70,(branches.offsetHeight-root.offsetHeight)/2+30)+'px';const svg=$('connections');svg.replaceChildren();const midY=root.offsetTop+root.offsetHeight/2;[...branches.children].forEach((card,i)=>{const right=i%2===1,x=card.offsetLeft+30+(right?0:card.offsetWidth),y=card.offsetTop+30+card.offsetHeight/2,startX=right?805:615;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M ${startX} ${midY} C ${(startX+x)/2} ${midY}, ${(startX+x)/2} ${y}, ${x} ${y}`);path.setAttribute('fill','none');path.setAttribute('stroke',palette[Math.floor(i/2)%palette.length]);path.setAttribute('stroke-opacity','.32');path.setAttribute('stroke-width','1.5');svg.append(path)})}
function setZoom(value){zoom=Math.max(.25,Math.min(1.5,value));$('map').style.zoom=zoom;$('zoom-label').textContent=Math.round(zoom*100)+'%'}
function fitCompact(){const grid=$('branches'),count=grid.children.length;if(!count)return;const width=grid.clientWidth,height=grid.clientHeight;const maxColumns=Math.max(1,Math.min(count,Math.floor(width/110)));let columns=maxColumns;for(let c=1;c<=maxColumns;c++){const rows=Math.ceil(count/c);grid.style.gridTemplateColumns=`repeat(${c},minmax(0,1fr))`;grid.style.gridTemplateRows=`repeat(${rows},minmax(0,1fr))`;const available=(height-(rows-1)*8)/rows;const fits=[...grid.children].every(card=>card.querySelector('.area-title').scrollHeight+(card.querySelector('.chip')?26:0)+16<=available);if(fits){columns=c;break}}grid.style.gridTemplateColumns=`repeat(${columns},minmax(0,1fr))`;grid.style.gridTemplateRows=`repeat(${Math.ceil(count/columns)},minmax(0,1fr))`}
function setView(mode){viewMode=mode;const compact=mode==='compact';$('viewport').classList.toggle('compact',compact);$('view-map').setAttribute('aria-pressed',String(!compact));$('view-compact').setAttribute('aria-pressed',String(compact));document.querySelector('.zoom').hidden=compact;$('view-hint').textContent=compact?'Arraste uma pessoa para uma área ou selecione a pessoa e clique no título.':'Clique no título de uma área para ver seus assuntos';$('map').style.zoom=compact?1:zoom;$('branches').style.gridTemplateColumns='';$('branches').style.gridTemplateRows='';$('viewport').scrollTo(0,0);try{localStorage.setItem('mapa-daily-view',mode)}catch{}render()}
$('view-map').onclick=()=>setView('map');$('view-compact').onclick=()=>setView('compact');
$('plus').onclick=()=>setZoom(zoom+.1);$('minus').onclick=()=>setZoom(zoom-.1);$('fit').onclick=()=>{setZoom(($('viewport').clientWidth-24)/1450);$('viewport').scrollTo(0,0)};
$('search').addEventListener('input',render);
palette.forEach(c=>{const b=el('button',c===color?'active':'');b.type='button';b.style.setProperty('--person-color',c);b.setAttribute('aria-label','Cor '+c);b.setAttribute('aria-pressed',String(c===color));b.onclick=()=>{color=c;[...$('colors').children].forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))})};$('colors').append(b)});
$('employee-form').addEventListener('submit',e=>{e.preventDefault();const name=$('name').value.trim();if(!name){$('name').focus();return}state.employees.push({id:crypto.randomUUID(),name,role:$('role').value.trim(),color});save();$('name').value='';$('role').value='';render();$('name').focus();toast('Funcionário cadastrado.')});
function unassign(id){if(!id||!state.employees.some(e=>e.id===id)){toast('Selecione uma pessoa primeiro.');return}state.assignments[id]=[];save();render();toast('Alocações removidas.')}dropTarget($('unassign'),unassign);$('unassign').onclick=()=>unassign(selected);$('unassign').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();unassign(selected)}};
function parseCSV(text){text=text.replace(/^\uFEFF/,'');const first=text.split(/\r?\n/)[0],delimiter=first.includes(';')?';':',';const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===delimiter&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell=''}else cell+=c}if(quoted)throw Error('O CSV contém aspas não fechadas.');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);const normalize=s=>s.trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const head=(rows.shift()||[]).map(normalize),ai=head.indexOf('area'),ti=head.indexOf('assuntos');if(ai<0||ti<0)throw Error('O CSV precisa das colunas Área e Assuntos.');if(!rows.length||rows.length>500)throw Error('Importe entre 1 e 500 áreas.');return rows.map((r,i)=>{if(!r[ai]?.trim()||r[ti]===undefined)throw Error('Linha '+(i+2)+' inválida.');return {id:crypto.randomUUID(),name:r[ai].trim(),topics:r[ti].split(';').map(t=>t.trim()).filter(Boolean)}})}
$('csv').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error('O CSV deve ter até 2 MB.');const areas=parseCSV(await file.text());if(!confirm('Substituir as áreas pelo novo CSV? As alocações atuais serão removidas. Os funcionários serão mantidos.'))return;state.areas=areas;state.assignments={};state.source=file.name;save();render();toast('CSV importado: '+areas.length+' áreas.')}catch(err){toast(err.message)}finally{e.target.value=''}};
$('backup').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='mapa-daily-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('restore').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5000000)throw Error('O backup deve ter até 5 MB.');const loaded=JSON.parse(await file.text());if(!validState(loaded))throw Error('Este arquivo não é um backup válido.');if(!confirm('Restaurar este backup e substituir os dados atuais?'))return;state=loaded;selected=null;save();render();toast('Backup restaurado.')}catch(err){toast(err instanceof SyntaxError?'Arquivo JSON inválido.':err.message)}finally{e.target.value=''}};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){selected=null;render()}});window.addEventListener('resize',drawLines);
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'list_daily_map',description:'Lista áreas, funcionários e alocações desta daily neste navegador.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>JSON.parse(JSON.stringify(state))});document.modelContext.registerTool({name:'assign_employee_to_area',description:'Aloca um funcionário cadastrado em uma área do mapa da daily e salva neste navegador.',inputSchema:{type:'object',properties:{employeeId:{type:'string'},areaId:{type:'string'}},required:['employeeId','areaId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input.employeeId!=='string'||typeof input.areaId!=='string')throw Error('Informe employeeId e areaId.');assign(input.employeeId,input.areaId);return{employeeId:input.employeeId,areas:state.assignments[input.employeeId]}}})}catch{}}
render();setZoom(1);try{if(localStorage.getItem('mapa-daily-view')==='compact')setView('compact')}catch{}



